# https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml
on:
  push:
    branches: main
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Cada dia a les 00:00
    - cron:  '0 0 * * *'

name: Render and Publish
permissions:
    contents: write
    pages: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: sf, osmdata, tinytable

      - name: Download osm data
        run: Rscript -e 'source("scripts/02_download_osm_data.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data_web/comarques.gpkg
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
