---
title: "Camins d'Aigua"
subtitle: "Seguiment introducció de dades de rieres, rierols i recs a OSM Catalunya"
author: "Marc Bosch i Matas"
format: html
warning: false
message: false
echo: false
---

```{r}
library(tinytable)
library(sf)
url <- "https://github.com/OSM-Catalan/caminsdaigua/raw/main/data_web/data_quarto.gpkg"
comarques <- st_read(url,
                     quiet = TRUE)
```



```{r}


comarques_nogeom <- st_drop_geometry(comarques)


```


# Seguiment per comarques


:::: {.columns}

::: {.column width="75%"}


```{r}


comarques_nogeom$length_osm <- (comarques_nogeom$length_osm / 1000) |>
  scales::comma(big.mark = ".",
                decimal.mark =  ",")

comarques_nogeom$length_icgc <- (comarques_nogeom$length_icgc / 1000) |>
  scales::comma(big.mark = ".",
                decimal.mark =  ",")

comarques_nogeom$ratio <- scales::percent(comarques_nogeom$ratio,
                                          decimal.mark = ",", accuracy = .01)

tt(comarques_nogeom)
```

:::

::: {.column width="5%"}
<!-- empty column to create gap -->
:::

::: {.column width="20%"}
```{r}
#| output: asis

licgc <- round(sum(comarques$length_icgc) / 1000, 2)
cat("Longitud cursos d'aigua ICGC: ", paste(scales::comma(licgc,
                                                          big.mark = ".",
                                                          decimal.mark =  ","),
                                            " km"))
```
```{r}
#| output: asis

losm <- round(sum(comarques$length_osm) / 1000, 2)
cat("Longitud cursos d'aigua OSM: ", paste(scales::comma(losm,
                                                         big.mark = ".",
                                                         decimal.mark =  ","),
                                           " km"))
```
```{r}
#| output: asis

perc <- sum(comarques$length_osm) / sum(comarques$length_icgc)
cat("Percentatge de cursos d'aigua a OSM: ", scales::percent(perc, .01))
```

:::

::::



# Mapes

```{r}
#| layout-nrow: 2
#| layout-ncol: 2
par(mfrow = c(2, 2))
comarques$length_icgc <- comarques$length_icgc / 1000
comarques$length_osm <- comarques$length_osm / 1000


plot(comarques["length_icgc"], breaks = "equal",
     nbreaks = 5,
     main = "Llargada ICGC", reset = FALSE)

plot(comarques["length_osm"], breaks = "equal",
     nbreaks = 5,
     main = "Llargada OSM", reset = FALSE)

plot(comarques["ratio"], breaks = c(0, .25, .5, .75, 1, max(comarques$ratio)),
     main = "Ràtio OSM/ICGC", reset = FALSE)
```


